columnSuffix: bokedbej
contentColumnType: text
handle: bannerLink
instructions: 'A fully qualified URL.'
name: 'Banner Link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
