defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7f94d647-d301-487a-8546-fc72a82bb31b # About
handle: about
maxAuthors: 1
minAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  68041276-7b3d-498b-9a92-f36db2dfe659: # Celeste Hanlon
    enabledByDefault: true
    hasUrls: true
    template: _about.twig
    uriFormat: about
type: single
